module.exports = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 9,
    DEFAULT_SALT: 7,
    DEFAULT_PORT: 5000,
    CHECK_RESULT: 0,
    ERROR_DETAILS_INDEX: 0,
    MIN_PASSWORDnEMAIL_LENGHT: 6,
    MIN_DATE_HOURS: 24,
    MAX_DATE_YEAR: 1,
    MIN_KEYWORD_LENGHT: 2,
    DEFAULT_SUCCESS_STATUS_CODE: 200
}